[icons]
# font awesome
firefox = "ï‰©"
kitty = "ï„ "
slack = "ï†˜"
emacs = "âŒ¨"
nheko = "ğŸˆ"
zotero = "ğŸ“š"
calibre = "ğŸ“š"
signal = "ğŸ”’"
psst = "ğŸ¶"
zoom = "ğŸ“¹"
discord = "ğŸ’¬"
bitwarden = "ğŸ”’"
ghostty = "ï„ "

[aliases.class]
Slack = "slack"
Emacs = "emacs"
Zotero = "zotero"
Signal = "signal"
".*action=join.*" = "zoom"
".*launch?.*" = "zoom"
Discord = "discord"
Bitwarden = "bitwarden"
".*ghostty" = "ghostty"

[aliases.app_id]
Slack = "slack"
Emacs = "emacs"
Zotero = "zotero"
Signal = "signal"
".*action=join.*" = "zoom"
".*launch?.*" = "zoom"
Discord = "discord"
Bitwarden = "bitwarden"
".*ghostty" = "ghostty"

[general]
separator = " î‚± "
default_icon = "?"
wm_property = "class"

[options]
remove_duplicates = true
no_names = false
no_icon_names = false
