
[icons]
# font awesome
firefox = "ï‰©"
kitty = "ï„ "
slack = "ï†˜"
deluge = "ïƒ"
emacs = "âŒ¨"
nheko = "ğŸˆ"
zotero = "ğŸ“š"
calibre = "ğŸ“š"
signal = "ğŸ”’"
psst = "ğŸ¶"
zoom = "ğŸ“¹"
discord = "ğŸ’¬"

[aliases]
Slack = "slack"
Deluge-gtk = "deluge"
Emacs = "emacs"
Zotero = "zotero"
Signal = "signal"
Psst-gui = "psst"
".*action=join.*" = "zoom"
".*launch?.*" = "zoom"
Discord = "discord"

[general]
separator = " î‚± "
default_icon = "ï„‘"
wm_property = "class"

[options]
remove_duplicates = true
no_names = false
no_icon_names = false
